### ISSUE TITLE
Output issue

### ISSUE THREAD

**Issue by nrius** [grocsvs/grocsvs#26]
Hello,
I have run grocsvs 3 times, on 3 different control-tumor pairs (1-2, 1-3 and 4-5), each with aprox 36x coverage and there are things I can't understand in the outputs.

First, I can't open the QCStep/report.pdf of the first one, although I have no problems with the files of the second and third runs.

But the most strange thing is the genotype.tsv file of the third, where all the expected columns are present, but in the wrong order. Additionally, some values are missing from some columns.

This is the normal column order that I got in the first and second runs:

chromx	x	chromy	y	orientation	cluster	kind	assembled	shared	total	Normal_p_resampling	Normal_shared	Normal_total	Normal_x_hap0	Normal_x_hap1	Normal_y_hap0	Normal_y_hap1	Tumor_p_resampling	Tumor_shared	Tumor_total	Tumor_x_hap0	Tumor_x_hap1	Tumor_y_hap0	Tumor_y_hap1	Normal_lengths_50	Normal_lengths_90	Tumor_lengths_50Tumor_lengths_90	frag_length_passes	nearby_snvs	blacklist	quality	cluster_size	dist

This is the one I got in the third run:

Normal_lengths_50	Normal_lengths_90	Normal_p_resampling	Normal_shared	Normal_total	Normal_x_hap0	Normal_x_hap1	Normal_y_hap0	Normal_y_hap1	Tumor_lengths_50	Tumor_lengths_90	Tumor_p_resampling	Tumor_shared	Tumor_total	Tumor_x_hap0	Tumor_x_hap1	Tumor_y_hap0	Tumor_y_hap1	assembled	blacklist	chromx	chromy	cluster	frag_length_passes	kind	nearby_snvs	orientation	quality	shared	total	x	y	cluster_size	dist 

From one run to another I've only changed the bam files and the id names. The only abnormal thing I can think of, it's that grocsvs was interrupted several times because I have problems with the multiprocessing parameters. Could this be the cause? I can't trust any of the results now, and I don't know if relaunching it is going to solve it.

Thanks

**Comment by nspies** [comment]
The order of columns in the genotypes.tsv file is somewhat random, which I agree can be somewhat confusing. It would be easy to add a line or two to grocsvs to ensure that the order remains constant, however if you need a well-formatted output file, I suggest you use the vcf file. This should contain most of the important outputs and conforms to the vcf standard.

Missing values should be fine in some columns of this file.

Without more details on the report file, I'm not sure what's going on. In order to generate this file, rpy2 does need to be installed, so perhaps this is the result of running your code on different servers with different software packages installed? If you use a text editor to open the first one, does it [look like a text file instead of a pdf](https://github.com/grocsvs/grocsvs/blob/master/src/grocsvs/stages/qc.py#L125)?

**Comment by nrius** [comment]
Hi,

Thanks for your answer, I am only using the vcf files now. The missing values (F50, F90 and PR) are only missing in one sample for calls that are complete in the other. So this makes sense now. Maybe in future updates a "nan" could help newcomers like me.

About the report, it was my fault, when I run grocsvs the first time, rpy2 was not installed.

I have a new doubt, in the PostprocesseingStep/summary.txt file, in the breakpoints section, the n=1, n=2, etc what does it stands for? I though it was the number of events with 1, 2, etc breakpoints involved, but this doesn't add up.

Thank you

**Comment by nrius** [comment]
Nevermind, I understood.

Every two lines in the vcf file correspond to an ID (or a region where a breakpoint is expected), this is why events always involve an even number of vcf lines.

Sorry for the confusion and thank you for your answer.
