### ISSUE TITLE
Events 

### ISSUE THREAD

**Issue by nrius** [grocsvs/grocsvs#27]
Hello,

I have run grocsvs several times now, and every time, there is a discrepancy between the number of events reported in the summary.txt for each sample (Normal and Tumor) and the number of events reported in the vcf  (events genotyped in each sample (GT=1)). Can you tell me what do you use to built the summary table? Are these differences normal?

Thanks for your time

Nuria

**Comment by nrius** [comment]
Hi again,

Sorry but I have another doubt. Do you know what is the difference between your QC report "fragment length mean" and Longranger's "molecule mean length"? I thought they were measuring the same, but my values are, not only very different (table below), but do not follow the same pattern.



    Longranger              grocsvs
    molecule mean length    fragment length mean
    53915.9935947188        19839
    51769.1518493565        17720
    56451.2951162177        15258
    64607.8674056633        21199
    63189.1323266687        21005
    66206.2115272529        15601

**Comment by nspies** [comment]
With respect to the second question, grocsvs uses a strategy similar to that employed by longranger to call read clouds. However, given that the primary purpose of grocsvs is to call SVs (whereas longranger emphasizes its phasing capabilities), the fragments called by grocsvs will tend to be much more conservative, allowing for the detection of fragments that have been split apart due to a modestly sized SV. I think most of the fragments should be the same length, however grocsvs won't have the same long tail of fragments -- you probably won't see such large discrepancies if you use a median fragment length measurement, rather than mean.

I'm not entirely sure what's going on with the different lists you refer to. I believe the vcf and summaries should have the same total list of events though some events may be genotyped as present in all/some (and maybe even none) of the samples.
