### ISSUE TITLE
what does "assembled" mean?

### ISSUE THREAD

**Issue by chen42** [grocsvs/grocsvs#28]
Dear Noah,

I am very glad to find groc-svs because it does exactly what I need to do. I finished my first run on two samples and am now looking at the results. I was not able to figure out what "Assembled" means. For example, I have in PostprocessingStep/summary.txt:
```
total breakpoints       3713
breakpoints     
               n=1      3484
               n=2      99
               n=3      5
               n=4      4
assembled       93 (3%)
``` 
Trying to trace the code on this and it seems assembled is be based on walkAssembly but I was not able to figure out more. 

Also, are the Event *number* in the svs.vcf file the same as the AssemblyStep/assembly.*number*?

Thank you very much for your help!

**Comment by nspies** [comment]
Hi!

I'm not entirely sure what your first question is getting at, but generally "assembled" means that there is a sequence assembly derived from 10x reads spanning a putative event such that the assembly supports the original event -- part of the assembled sequence maps upstream of the SV breakpoint, part of it maps downstream. These events, in addition to having full nucleotide sequence resolution (eg if there are some additional micro-insertions at the breakpoint) are also generally the most confident SV calls, as it's very unlikely to be able to create a sequence assembly from a false-positive event.

I don't think the event numbers correspond to the assembly number as there's a re-clustering step following assembly, but honestly it's been about a year since I last run groc-svs (I've finished my postdoc) and I'm not 100% certain on this.
