### ISSUE TITLE
ValueError: invalid contig `hs37d5`

### ISSUE THREAD

**Issue by morispi** [grocsvs/grocsvs#34]
Hello,

I'm attempting to run grocsvs on the following 10x Genomics BAM file (ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/10Xgenomics_ChromiumGenome/), and on the following 10x Genomics reference genome (https://support.10xgenomics.com/genome-exome/software/downloads/latest, hg19).

However, grocsvs stops and reports an error that contig 'hs37d5' is invalid. You can find the log here: 
[log.txt](https://github.com/grocsvs/grocsvs/files/5378287/log.txt), and the configuration file I used here: 
[config.txt](https://github.com/grocsvs/grocsvs/files/5378288/config.txt).

I ran another experiment after removing the 'hs37d5' contig and its associated sequence from the reference genome file. All seems to go well so far. However, I don't fully understand why this contig causes issues, since both the BAM and reference genome files were provided by 10x Genomics?

Best,
Pierre

**Comment by nspies-celsiustx** [comment]
I'm not entirely sure how you've done the alignments, but I'm guessing you've aligned using longranger and that they're removing alignments that hit the decoy "hs37d5" contig so it doesn't show up in your bam file even though it's in your fasta file. I think you've done exactly the right thing, which is to remove it from your fasta reference file so it's not included in the analyses.

I would, however, strongly recommend using hg38 rather than hg19 if possible! Many of the structural variants that will show up with grocsvs in hg19 are really genome errors that have been corrected/completed in hg38.

**Comment by morispi** [comment]
Hi,

I did not perform alignment myself, but directly downloaded the BAM file with the link provided above. I think the alignment was performed with LongRanger anyway. I guess you're right, and hs37d5 doesn't show up in the BAM file. Since both BAM and reference files were provided by LongRanger / 10x, I thought they'd be directly compatible. Great to know I did the right thing though, thanks!

I'm only using hg19 for testing purposes, I want to compare a few tools to a VCF available here (ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/analysis/NIST_SVs_Integration_v0.6/), and for which hg19 was used. Thanks for the advice anyway, I'll be sure to update to hg38 for performing more robust experiments.

Best,
Pierre
